modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/Alex-the-666/Rats/issues" #optional
[[mods]] #mandatory
modId="rats" #mandatory
version="4.0.0" #mandatory
displayName="Rats" #mandatory
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/rats/files" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/rats" #optional
logoFile="rats_logo.png" #optional
authors="Alexthe666" #optional
description='''
Rats.
'''
[[dependencies.rats]] #optional
    # the modid of the dependency
    modId="citadel" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[1.0.1,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="AFTER"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"